name: toolchain

on: 
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Prepare toolchain
        run: |
          cd toolchain-mipsel
          ./build_toolchain
          cd toolchain-4.4.x
          tar cJf ../mipsel-linux-uclibc.tar.xz .
      - name: Upload toolchain
        uses: actions/upload-artifact@v3
        with:
          name: toolchain
          path: toolchain-mipsel/mipsel-linux-uclibc.tar.xz
